<a href="https://colab.research.google.com/github/lamyeamaha/tensorflow-codes/blob/main/TensorFlow_Intro_with_mnist_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Hello World 1**

*Key points done in code*
- uses the mnist dataset of digits from 0 - 9
learning tasks
- scaling
- confustion matrix, classification report from sklearn


**About Tensorflow:**

***tensorflow ***- a open source machine learning library -  used mainly for deep

***Key features of tensorflow:***

***Tensors:*** Tensors are multi-dimensional arrays, which are the fundamental data structures in TensorFlow. These tensors flow through the computational graph, carrying data between operations.

***Automatic Differentiation:*** TensorFlow can automatically compute gradients of mathematical functions, which is essential for optimization algorithms used in training neural networks through backpropagation.

***Support for GPUs and TPUs:*** TensorFlow can harness the power of Graphics Processing Units (GPUs) and Tensor Processing Units (TPUs) to accelerate computation and training significantly, especially for deep learning models.

***Model Deployment:*** TensorFlow allows models to be deployed on various platforms, including mobile devices, web browsers, and servers.

In [ ]:
import tensorflow as tf
import numpy as np

**MNIST Dataset**

In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [ ]:
type(x_train)

numpy.ndarray

In [ ]:
x_train[:1]

array([[[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           3,  18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,
           0,   0,   0

In [ ]:
x_train, x_test = x_train/255.0, x_test/255.0

In [ ]:
x_train[:1]

array([[[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.

In [ ]:
unique_values, counts = np.unique(y_train, return_counts=True)
print(unique_values)
print(counts)

[0 1 2 3 4 5 6 7 8 9]
[5923 6742 5958 6131 5842 5421 5918 6265 5851 5949]


In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation = 'softmax')
])

In [ ]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
model.fit(x_train,y_train, epochs=2)

Epoch 1/2
1875/1875 [==============================] - 11s 5ms/step - loss: 0.2981 - accuracy: 0.9141
Epoch 2/2
1875/1875 [==============================] - 7s 3ms/step - loss: 0.1432 - accuracy: 0.9573


In [ ]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.1005 - accuracy: 0.9680


[0.10050643235445023, 0.9679999947547913]

In [ ]:


y_pred = model.predict(x_test)

y_pred.shape

313/313 [==============================] - 1s 2ms/step


(10000, 10)

In [ ]:
y_pred[1]

array([2.10708231e-06, 3.49847629e-04, 9.99493897e-01, 1.05382904e-04,
       1.19910462e-11, 5.58723104e-06, 1.03457512e-06, 1.83635873e-09,
       4.18851341e-05, 1.27348382e-10], dtype=float32)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
y_pred_classes = np.argmax(y_pred, axis = 1)
y_pred_classes


array([7, 2, 1, ..., 4, 5, 6])

In [ ]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [ ]:
# Create the confusion matrix
cm = confusion_matrix(y_test, y_pred_classes)
cm

array([[ 967,    0,    0,    1,    1,    1,    7,    1,    2,    0],
       [   0, 1124,    2,    2,    0,    1,    2,    1,    3,    0],
       [   7,    3,  990,   10,    3,    0,    4,    8,    7,    0],
       [   0,    0,    4,  985,    0,    6,    0,   10,    5,    0],
       [   1,    0,    7,    0,  948,    0,    5,    3,    2,   16],
       [   6,    0,    0,   15,    1,  855,    6,    2,    5,    2],
       [   6,    3,    1,    0,    6,   10,  925,    0,    7,    0],
       [   1,    6,   12,    3,    0,    0,    0, 1002,    0,    4],
       [   5,    3,    4,   13,    4,    5,    3,    9,  926,    2],
       [   4,    6,    1,   10,   12,    4,    1,   10,    3,  958]])

In [ ]:
print(classification_report(y_test, y_pred_classes))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       0.98      0.99      0.99      1135
           2       0.97      0.96      0.96      1032
           3       0.95      0.98      0.96      1010
           4       0.97      0.97      0.97       982
           5       0.97      0.96      0.96       892
           6       0.97      0.97      0.97       958
           7       0.96      0.97      0.97      1028
           8       0.96      0.95      0.96       974
           9       0.98      0.95      0.96      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

